### ISSUE TITLE
Cant open Endless backpack

### ISSUE THREAD

**Issue by killerkitt** [Draylar/inmis#125]
[18:16:47] [Server thread/ERROR]: Error executing task on Server
java.lang.ArrayIndexOutOfBoundsException: Index 117 out of bounds for length 117
        at java.util.Arrays$ArrayList.set(Arrays.java:4170) ~[?:?]
        at net.minecraft.class_2371.set(class_2371.java:54) ~[server-intermediary.jar:?]
        at net.minecraft.class_1277.method_5447(class_1277.java:136) ~[server-intermediary.jar:?]
        at draylar.inmis.util.InventoryUtils.lambda$fromTag$0(InventoryUtils.java:30) ~[inmis-2.6.0-1.18.2.jar:?]
        at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?]
        at draylar.inmis.util.InventoryUtils.fromTag(InventoryUtils.java:26) ~[inmis-2.6.0-1.18.2.jar:?]
        at draylar.inmis.ui.BackpackScreenHandler.setupContainer(BackpackScreenHandler.java:61) ~[inmis-2.6.0-1.18.2.jar:?]
        at draylar.inmis.ui.BackpackScreenHandler.<init>(BackpackScreenHandler.java:39) ~[inmis-2.6.0-1.18.2.jar:?]
        at draylar.inmis.item.BackpackItem$1.createMenu(BackpackItem.java:71) ~[inmis-2.6.0-1.18.2.jar:?]
        at net.minecraft.class_3222.method_17355(class_3222.java:1031) ~[server-intermediary.jar:?]
        at draylar.inmis.item.BackpackItem.openScreen(BackpackItem.java:58) ~[inmis-2.6.0-1.18.2.jar:?]
        at draylar.inmis.network.ServerNetworking.lambda$receiveOpenBackpackPacket$1(ServerNetworking.java:46) ~[inmis-2.6.0-1.18.2.jar:?]
        at net.minecraft.class_3738.run(class_3738.java:18) ~[server-intermediary.jar:?]
        at net.minecraft.class_1255.method_18859(class_1255.java:157) ~[server-intermediary.jar:?]
        at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:808) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:165) ~[server-intermediary.jar:?]
        at net.minecraft.class_1255.method_16075(class_1255.java:131) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:790) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:784) ~[server-intermediary.jar:?]
        at net.minecraft.class_1255.method_5383(class_1255.java:116) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:768) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:701) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:273) ~[server-intermediary.jar:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]

**Comment by killerkitt** [comment]
update i changed the size back to default and now i get ghost items in my inventory

**Comment by killerkitt** [comment]
please close it is due tot he size of the backpack when it was changed in config

**Comment by Elatax** [comment]
@killerkitt you need to change it on server and client config.
