### ISSUE TITLE
[disconnect] Cannot invoke getInventoryTitle because inventory is null

### ISSUE THREAD

**Issue by DemonMartin** [Draylar/inmis#136]
Not Sure how to reprocude this, but I was just taking out some random items out of the backpack and this happened and kicked me from the server (Playing on Fabrinaz Modpack v0.1.6)
> [Server thread/ERROR]: Failed to handle packet net.minecraft.class_2885@3dd57c9c, suppressing error
java.lang.NullPointerException: Cannot invoke "ninjaphenix.container_library.api.v2.OpenableBlockEntityV2.getInventoryTitle()" because "inventory" is null
        at Not Enough Crashes deobfuscated stack trace.(1.18.2+build.4) ~[?:?]
        at ninjaphenix.container_library.wrappers.NetworkWrapper.s_openInventory(NetworkWrapper.java:31) ~[ninjaphenix-container-library-1.3.0+1.18-fabric.jar:?]
        at ninjaphenix.container_library.api.v2.OpenableBlockEntityProviderV2.ncl_sOpenInventory(OpenableBlockEntityProviderV2.java:86) ~[ninjaphenix-container-library-1.3.0+1.18-fabric.jar:?]
        at ninjaphenix.container_library.api.v2.OpenableBlockEntityProviderV2.ncl_sOpenInventory(OpenableBlockEntityProviderV2.java:79) ~[ninjaphenix-container-library-1.3.0+1.18-fabric.jar:?]
        at ninjaphenix.container_library.api.v2.OpenableBlockEntityProviderV2.ncl_onBlockUse(OpenableBlockEntityProviderV2.java:49) ~[ninjaphenix-container-library-1.3.0+1.18-fabric.jar:?]
        at ninjaphenix.expandedstorage.block.OpenableBlock.onUse(OpenableBlock.java:105) ~[expandedstorage-7.3.12+1.18.2.jar:?]
        at net.minecraft.block.AbstractBlock$AbstractBlockState.onUse(AbstractBlock:939) ~[?:?]
        at net.minecraft.server.network.ServerPlayerInteractionManager.interactBlock(ServerPlayerInteractionManager:336) ~[?:?]
        at net.minecraft.server.network.ServerPlayNetworkHandler.onPlayerInteractBlock(ServerPlayNetworkHandler:1081) ~[?:?]
        at net.minecraft.network.packet.c2s.play.PlayerInteractBlockC2SPacket.apply(PlayerInteractBlockC2SPacket:30) ~[?:?]
        at net.minecraft.network.packet.c2s.play.PlayerInteractBlockC2SPacket.apply(PlayerInteractBlockC2SPacket:8) ~[?:?]
        at net.minecraft.network.NetworkThreadUtils.method_11072(NetworkThreadUtils:22) ~[?:?]
        at net.minecraft.server.ServerTask.run(ServerTask:18) ~[?:?]
        at net.minecraft.util.thread.ThreadExecutor.executeTask(ThreadExecutor:157) ~[?:?]
        at net.minecraft.util.thread.ReentrantThreadExecutor.executeTask(ReentrantThreadExecutor:23) ~[?:?]
        at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer:808) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer:165) ~[server-intermediary.jar:?]
        at net.minecraft.util.thread.ThreadExecutor.runTask(ThreadExecutor:131) ~[?:?]
        at net.minecraft.server.MinecraftServer.runOneTask(MinecraftServer:790) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.runTask(MinecraftServer:784) ~[server-intermediary.jar:?]
        at net.minecraft.util.thread.ThreadExecutor.runTasks(ThreadExecutor:140) ~[?:?]
        at net.minecraft.server.MinecraftServer.runTasksTillTickEnd(MinecraftServer:769) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer:701) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer:273) ~[server-intermediary.jar:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]
[01:19:56] [Server thread/ERROR]: Failed to handle packet net.minecraft.class_2885@100608cf, suppressing error
java.lang.NullPointerException: Cannot invoke "ninjaphenix.container_library.api.v2.OpenableBlockEntityV2.getInventoryTitle()" because "inventory" is null
        at Not Enough Crashes deobfuscated stack trace.(1.18.2+build.4) ~[?:?]
        at ninjaphenix.container_library.wrappers.NetworkWrapper.s_openInventory(NetworkWrapper.java:31) ~[ninjaphenix-container-library-1.3.0+1.18-fabric.jar:?]
        at ninjaphenix.container_library.api.v2.OpenableBlockEntityProviderV2.ncl_sOpenInventory(OpenableBlockEntityProviderV2.java:86) ~[ninjaphenix-container-library-1.3.0+1.18-fabric.jar:?]
        at ninjaphenix.container_library.api.v2.OpenableBlockEntityProviderV2.ncl_sOpenInventory(OpenableBlockEntityProviderV2.java:79) ~[ninjaphenix-container-library-1.3.0+1.18-fabric.jar:?]
        at ninjaphenix.container_library.api.v2.OpenableBlockEntityProviderV2.ncl_onBlockUse(OpenableBlockEntityProviderV2.java:49) ~[ninjaphenix-container-library-1.3.0+1.18-fabric.jar:?]
        at ninjaphenix.expandedstorage.block.OpenableBlock.onUse(OpenableBlock.java:105) ~[expandedstorage-7.3.12+1.18.2.jar:?]
        at net.minecraft.block.AbstractBlock$AbstractBlockState.onUse(AbstractBlock:939) ~[?:?]
        at net.minecraft.server.network.ServerPlayerInteractionManager.interactBlock(ServerPlayerInteractionManager:336) ~[?:?]
        at net.minecraft.server.network.ServerPlayNetworkHandler.onPlayerInteractBlock(ServerPlayNetworkHandler:1081) ~[?:?]
        at net.minecraft.network.packet.c2s.play.PlayerInteractBlockC2SPacket.apply(PlayerInteractBlockC2SPacket:30) ~[?:?]
        at net.minecraft.network.packet.c2s.play.PlayerInteractBlockC2SPacket.apply(PlayerInteractBlockC2SPacket:8) ~[?:?]
        at net.minecraft.network.NetworkThreadUtils.method_11072(NetworkThreadUtils:22) ~[?:?]
        at net.minecraft.server.ServerTask.run(ServerTask:18) ~[?:?]
        at net.minecraft.util.thread.ThreadExecutor.executeTask(ThreadExecutor:157) ~[?:?]
        at net.minecraft.util.thread.ReentrantThreadExecutor.executeTask(ReentrantThreadExecutor:23) ~[?:?]
        at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer:808) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer:165) ~[server-intermediary.jar:?]
        at net.minecraft.util.thread.ThreadExecutor.runTask(ThreadExecutor:131) ~[?:?]
        at net.minecraft.server.MinecraftServer.runOneTask(MinecraftServer:790) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.runTask(MinecraftServer:784) ~[server-intermediary.jar:?]
        at net.minecraft.util.thread.ThreadExecutor.runTasks(ThreadExecutor:116) ~[?:?]
        at net.minecraft.server.MinecraftServer.runTasksTillTickEnd(MinecraftServer:768) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer:701) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer:273) ~[server-intermediary.jar:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]
[01:19:58] [Server thread/ERROR]: Failed to handle packet net.minecraft.class_2885@7386ad98, suppressing error
java.lang.NullPointerException: Cannot invoke "ninjaphenix.container_library.api.v2.OpenableBlockEntityV2.getInventoryTitle()" because "inventory" is null
        at Not Enough Crashes deobfuscated stack trace.(1.18.2+build.4) ~[?:?]
        at ninjaphenix.container_library.wrappers.NetworkWrapper.s_openInventory(NetworkWrapper.java:31) ~[ninjaphenix-container-library-1.3.0+1.18-fabric.jar:?]
        at ninjaphenix.container_library.api.v2.OpenableBlockEntityProviderV2.ncl_sOpenInventory(OpenableBlockEntityProviderV2.java:86) ~[ninjaphenix-container-library-1.3.0+1.18-fabric.jar:?]
        at ninjaphenix.container_library.api.v2.OpenableBlockEntityProviderV2.ncl_sOpenInventory(OpenableBlockEntityProviderV2.java:79) ~[ninjaphenix-container-library-1.3.0+1.18-fabric.jar:?]
        at ninjaphenix.container_library.api.v2.OpenableBlockEntityProviderV2.ncl_onBlockUse(OpenableBlockEntityProviderV2.java:49) ~[ninjaphenix-container-library-1.3.0+1.18-fabric.jar:?]
        at ninjaphenix.expandedstorage.block.OpenableBlock.onUse(OpenableBlock.java:105) ~[expandedstorage-7.3.12+1.18.2.jar:?]
        at net.minecraft.block.AbstractBlock$AbstractBlockState.onUse(AbstractBlock:939) ~[?:?]
        at net.minecraft.server.network.ServerPlayerInteractionManager.interactBlock(ServerPlayerInteractionManager:336) ~[?:?]
        at net.minecraft.server.network.ServerPlayNetworkHandler.onPlayerInteractBlock(ServerPlayNetworkHandler:1081) ~[?:?]
        at net.minecraft.network.packet.c2s.play.PlayerInteractBlockC2SPacket.apply(PlayerInteractBlockC2SPacket:30) ~[?:?]
        at net.minecraft.network.packet.c2s.play.PlayerInteractBlockC2SPacket.apply(PlayerInteractBlockC2SPacket:8) ~[?:?]
        at net.minecraft.network.NetworkThreadUtils.method_11072(NetworkThreadUtils:22) ~[?:?]
        at net.minecraft.server.ServerTask.run(ServerTask:18) ~[?:?]
        at net.minecraft.util.thread.ThreadExecutor.executeTask(ThreadExecutor:157) ~[?:?]
        at net.minecraft.util.thread.ReentrantThreadExecutor.executeTask(ReentrantThreadExecutor:23) ~[?:?]
        at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer:808) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer:165) ~[server-intermediary.jar:?]
        at net.minecraft.util.thread.ThreadExecutor.runTask(ThreadExecutor:131) ~[?:?]
        at net.minecraft.server.MinecraftServer.runOneTask(MinecraftServer:790) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.runTask(MinecraftServer:784) ~[server-intermediary.jar:?]
        at net.minecraft.util.thread.ThreadExecutor.runTasks(ThreadExecutor:116) ~[?:?]
        at net.minecraft.server.MinecraftServer.runTasksTillTickEnd(MinecraftServer:768) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer:701) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer:273) ~[server-intermediary.jar:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]
[01:19:58] [Server thread/ERROR]: Failed to handle packet net.minecraft.class_2885@4b32272c, suppressing error
java.lang.NullPointerException: Cannot invoke "ninjaphenix.container_library.api.v2.OpenableBlockEntityV2.getInventoryTitle()" because "inventory" is null
        at Not Enough Crashes deobfuscated stack trace.(1.18.2+build.4) ~[?:?]
        at ninjaphenix.container_library.wrappers.NetworkWrapper.s_openInventory(NetworkWrapper.java:31) ~[ninjaphenix-container-library-1.3.0+1.18-fabric.jar:?]
        at ninjaphenix.container_library.api.v2.OpenableBlockEntityProviderV2.ncl_sOpenInventory(OpenableBlockEntityProviderV2.java:86) ~[ninjaphenix-container-library-1.3.0+1.18-fabric.jar:?]
        at ninjaphenix.container_library.api.v2.OpenableBlockEntityProviderV2.ncl_sOpenInventory(OpenableBlockEntityProviderV2.java:79) ~[ninjaphenix-container-library-1.3.0+1.18-fabric.jar:?]
        at ninjaphenix.container_library.api.v2.OpenableBlockEntityProviderV2.ncl_onBlockUse(OpenableBlockEntityProviderV2.java:49) ~[ninjaphenix-container-library-1.3.0+1.18-fabric.jar:?]
        at ninjaphenix.expandedstorage.block.OpenableBlock.onUse(OpenableBlock.java:105) ~[expandedstorage-7.3.12+1.18.2.jar:?]
        at net.minecraft.block.AbstractBlock$AbstractBlockState.onUse(AbstractBlock:939) ~[?:?]
        at net.minecraft.server.network.ServerPlayerInteractionManager.interactBlock(ServerPlayerInteractionManager:336) ~[?:?]
        at net.minecraft.server.network.ServerPlayNetworkHandler.onPlayerInteractBlock(ServerPlayNetworkHandler:1081) ~[?:?]
        at net.minecraft.network.packet.c2s.play.PlayerInteractBlockC2SPacket.apply(PlayerInteractBlockC2SPacket:30) ~[?:?]
        at net.minecraft.network.packet.c2s.play.PlayerInteractBlockC2SPacket.apply(PlayerInteractBlockC2SPacket:8) ~[?:?]
        at net.minecraft.network.NetworkThreadUtils.method_11072(NetworkThreadUtils:22) ~[?:?]
        at net.minecraft.server.ServerTask.run(ServerTask:18) ~[?:?]
        at net.minecraft.util.thread.ThreadExecutor.executeTask(ThreadExecutor:157) ~[?:?]
        at net.minecraft.util.thread.ReentrantThreadExecutor.executeTask(ReentrantThreadExecutor:23) ~[?:?]
        at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer:808) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer:165) ~[server-intermediary.jar:?]
        at net.minecraft.util.thread.ThreadExecutor.runTask(ThreadExecutor:131) ~[?:?]
        at net.minecraft.server.MinecraftServer.runOneTask(MinecraftServer:790) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.runTask(MinecraftServer:784) ~[server-intermediary.jar:?]
        at net.minecraft.util.thread.ThreadExecutor.runTasks(ThreadExecutor:116) ~[?:?]
        at net.minecraft.server.MinecraftServer.runTasksTillTickEnd(MinecraftServer:768) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer:701) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer:273) ~[server-intermediary.jar:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]
[01:20:08] [Server thread/INFO]: [STDOUT]: [Progressive Bosses] Player _DemonMartin_ spawned a Wither. Difficulty: 0
[01:20:28] [Server thread/INFO]: [STDOUT]: [Progressive Bosses] Player _DemonMartin_ spawned a Wither. Difficulty: 0
[01:20:32] [Server thread/ERROR]: Failed to handle packet net.minecraft.class_2885@3fd38718, suppressing error
java.lang.NullPointerException: Cannot invoke "ninjaphenix.container_library.api.v2.OpenableBlockEntityV2.getInventoryTitle()" because "inventory" is null
        at Not Enough Crashes deobfuscated stack trace.(1.18.2+build.4) ~[?:?]
        at ninjaphenix.container_library.wrappers.NetworkWrapper.s_openInventory(NetworkWrapper.java:31) ~[ninjaphenix-container-library-1.3.0+1.18-fabric.jar:?]
        at ninjaphenix.container_library.api.v2.OpenableBlockEntityProviderV2.ncl_sOpenInventory(OpenableBlockEntityProviderV2.java:86) ~[ninjaphenix-container-library-1.3.0+1.18-fabric.jar:?]
        at ninjaphenix.container_library.api.v2.OpenableBlockEntityProviderV2.ncl_sOpenInventory(OpenableBlockEntityProviderV2.java:79) ~[ninjaphenix-container-library-1.3.0+1.18-fabric.jar:?]
        at ninjaphenix.container_library.api.v2.OpenableBlockEntityProviderV2.ncl_onBlockUse(OpenableBlockEntityProviderV2.java:49) ~[ninjaphenix-container-library-1.3.0+1.18-fabric.jar:?]
        at ninjaphenix.expandedstorage.block.OpenableBlock.onUse(OpenableBlock.java:105) ~[expandedstorage-7.3.12+1.18.2.jar:?]
        at net.minecraft.block.AbstractBlock$AbstractBlockState.onUse(AbstractBlock:939) ~[?:?]
        at net.minecraft.server.network.ServerPlayerInteractionManager.interactBlock(ServerPlayerInteractionManager:336) ~[?:?]
        at net.minecraft.server.network.ServerPlayNetworkHandler.onPlayerInteractBlock(ServerPlayNetworkHandler:1081) ~[?:?]
        at net.minecraft.network.packet.c2s.play.PlayerInteractBlockC2SPacket.apply(PlayerInteractBlockC2SPacket:30) ~[?:?]
        at net.minecraft.network.packet.c2s.play.PlayerInteractBlockC2SPacket.apply(PlayerInteractBlockC2SPacket:8) ~[?:?]
        at net.minecraft.network.NetworkThreadUtils.method_11072(NetworkThreadUtils:22) ~[?:?]
        at net.minecraft.server.ServerTask.run(ServerTask:18) ~[?:?]
        at net.minecraft.util.thread.ThreadExecutor.executeTask(ThreadExecutor:157) ~[?:?]
        at net.minecraft.util.thread.ReentrantThreadExecutor.executeTask(ReentrantThreadExecutor:23) ~[?:?]
        at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer:808) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer:165) ~[server-intermediary.jar:?]
        at net.minecraft.util.thread.ThreadExecutor.runTask(ThreadExecutor:131) ~[?:?]
        at net.minecraft.server.MinecraftServer.runOneTask(MinecraftServer:790) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.runTask(MinecraftServer:784) ~[server-intermediary.jar:?]
        at net.minecraft.util.thread.ThreadExecutor.runTasks(ThreadExecutor:140) ~[?:?]
        at net.minecraft.server.MinecraftServer.runTasksTillTickEnd(MinecraftServer:769) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer:701) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer:273) ~[server-intermediary.jar:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]
[01:20:33] [Server thread/ERROR]: Failed to handle packet net.minecraft.class_2885@23ced44e, suppressing error
java.lang.NullPointerException: Cannot invoke "ninjaphenix.container_library.api.v2.OpenableBlockEntityV2.getInventoryTitle()" because "inventory" is null
        at Not Enough Crashes deobfuscated stack trace.(1.18.2+build.4) ~[?:?]
        at ninjaphenix.container_library.wrappers.NetworkWrapper.s_openInventory(NetworkWrapper.java:31) ~[ninjaphenix-container-library-1.3.0+1.18-fabric.jar:?]
        at ninjaphenix.container_library.api.v2.OpenableBlockEntityProviderV2.ncl_sOpenInventory(OpenableBlockEntityProviderV2.java:86) ~[ninjaphenix-container-library-1.3.0+1.18-fabric.jar:?]
        at ninjaphenix.container_library.api.v2.OpenableBlockEntityProviderV2.ncl_sOpenInventory(OpenableBlockEntityProviderV2.java:79) ~[ninjaphenix-container-library-1.3.0+1.18-fabric.jar:?]
        at ninjaphenix.container_library.api.v2.OpenableBlockEntityProviderV2.ncl_onBlockUse(OpenableBlockEntityProviderV2.java:49) ~[ninjaphenix-container-library-1.3.0+1.18-fabric.jar:?]
        at ninjaphenix.expandedstorage.block.OpenableBlock.onUse(OpenableBlock.java:105) ~[expandedstorage-7.3.12+1.18.2.jar:?]
        at net.minecraft.block.AbstractBlock$AbstractBlockState.onUse(AbstractBlock:939) ~[?:?]
        at net.minecraft.server.network.ServerPlayerInteractionManager.interactBlock(ServerPlayerInteractionManager:336) ~[?:?]
        at net.minecraft.server.network.ServerPlayNetworkHandler.onPlayerInteractBlock(ServerPlayNetworkHandler:1081) ~[?:?]
        at net.minecraft.network.packet.c2s.play.PlayerInteractBlockC2SPacket.apply(PlayerInteractBlockC2SPacket:30) ~[?:?]
        at net.minecraft.network.packet.c2s.play.PlayerInteractBlockC2SPacket.apply(PlayerInteractBlockC2SPacket:8) ~[?:?]
        at net.minecraft.network.NetworkThreadUtils.method_11072(NetworkThreadUtils:22) ~[?:?]
        at net.minecraft.server.ServerTask.run(ServerTask:18) ~[?:?]
        at net.minecraft.util.thread.ThreadExecutor.executeTask(ThreadExecutor:157) ~[?:?]
        at net.minecraft.util.thread.ReentrantThreadExecutor.executeTask(ReentrantThreadExecutor:23) ~[?:?]
        at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer:808) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer:165) ~[server-intermediary.jar:?]
        at net.minecraft.util.thread.ThreadExecutor.runTask(ThreadExecutor:131) ~[?:?]
        at net.minecraft.server.MinecraftServer.runOneTask(MinecraftServer:790) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.runTask(MinecraftServer:784) ~[server-intermediary.jar:?]
        at net.minecraft.util.thread.ThreadExecutor.runTasks(ThreadExecutor:116) ~[?:?]
        at net.minecraft.server.MinecraftServer.runTasksTillTickEnd(MinecraftServer:768) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer:701) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer:273) ~[server-intermediary.jar:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]
[01:20:33] [Server thread/ERROR]: Failed to handle packet net.minecraft.class_2885@598423ab, suppressing error
java.lang.NullPointerException: Cannot invoke "ninjaphenix.container_library.api.v2.OpenableBlockEntityV2.getInventoryTitle()" because "inventory" is null
        at Not Enough Crashes deobfuscated stack trace.(1.18.2+build.4) ~[?:?]
        at ninjaphenix.container_library.wrappers.NetworkWrapper.s_openInventory(NetworkWrapper.java:31) ~[ninjaphenix-container-library-1.3.0+1.18-fabric.jar:?]
        at ninjaphenix.container_library.api.v2.OpenableBlockEntityProviderV2.ncl_sOpenInventory(OpenableBlockEntityProviderV2.java:86) ~[ninjaphenix-container-library-1.3.0+1.18-fabric.jar:?]
        at ninjaphenix.container_library.api.v2.OpenableBlockEntityProviderV2.ncl_sOpenInventory(OpenableBlockEntityProviderV2.java:79) ~[ninjaphenix-container-library-1.3.0+1.18-fabric.jar:?]
        at ninjaphenix.container_library.api.v2.OpenableBlockEntityProviderV2.ncl_onBlockUse(OpenableBlockEntityProviderV2.java:49) ~[ninjaphenix-container-library-1.3.0+1.18-fabric.jar:?]
        at ninjaphenix.expandedstorage.block.OpenableBlock.onUse(OpenableBlock.java:105) ~[expandedstorage-7.3.12+1.18.2.jar:?]
        at net.minecraft.block.AbstractBlock$AbstractBlockState.onUse(AbstractBlock:939) ~[?:?]
        at net.minecraft.server.network.ServerPlayerInteractionManager.interactBlock(ServerPlayerInteractionManager:336) ~[?:?]
        at net.minecraft.server.network.ServerPlayNetworkHandler.onPlayerInteractBlock(ServerPlayNetworkHandler:1081) ~[?:?]
        at net.minecraft.network.packet.c2s.play.PlayerInteractBlockC2SPacket.apply(PlayerInteractBlockC2SPacket:30) ~[?:?]
        at net.minecraft.network.packet.c2s.play.PlayerInteractBlockC2SPacket.apply(PlayerInteractBlockC2SPacket:8) ~[?:?]
        at net.minecraft.network.NetworkThreadUtils.method_11072(NetworkThreadUtils:22) ~[?:?]
        at net.minecraft.server.ServerTask.run(ServerTask:18) ~[?:?]
        at net.minecraft.util.thread.ThreadExecutor.executeTask(ThreadExecutor:157) ~[?:?]
        at net.minecraft.util.thread.ReentrantThreadExecutor.executeTask(ReentrantThreadExecutor:23) ~[?:?]
        at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer:808) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer:165) ~[server-intermediary.jar:?]
        at net.minecraft.util.thread.ThreadExecutor.runTask(ThreadExecutor:131) ~[?:?]
        at net.minecraft.server.MinecraftServer.runOneTask(MinecraftServer:790) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.runTask(MinecraftServer:784) ~[server-intermediary.jar:?]
        at net.minecraft.util.thread.ThreadExecutor.runTasks(ThreadExecutor:116) ~[?:?]
        at net.minecraft.server.MinecraftServer.runTasksTillTickEnd(MinecraftServer:768) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer:701) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer:273) ~[server-intermediary.jar:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]

**Comment by DemonMartin** [comment]
Actually, wrong mod, Gold Expanded Storage Gold Chests is causing it.
