### ISSUE TITLE
Missing Cloth Config API dependency for 1.21 build

### ISSUE THREAD

**Issue by lowusage** [Draylar/inmis#175]
Hey,

Building the 1.21 branch here, in a clean root, and running the mod alongside the Fabric API mod leads to a ``java.lang.ClassNotFoundException: me.shedaniel.autoconfig.ConfigData`` error and crash.

A fix for this is to install the Cloth Config API, but it is not specified in README nor in curseforge dependencies.

I am not familiar enough with minecraft modding and/or fabric to know if it is me that miss a dependency at build or if Cloth Config API is missing from the running requirements.

Full crash report : 
```
---- Minecraft Crash Report ----
// Why is it breaking :(

Time: 2024-08-24 18:14:50
Description: Initializing game

java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'inmis' at 'draylar.inmis.Inmis'!
	at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:403)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:401)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:52)
	at net.minecraft.class_310.<init>(class_310.java:477)
	at net.minecraft.client.main.Main.main(Main.java:239)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:100)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)
Caused by: java.lang.NoClassDefFoundError: me/shedaniel/autoconfig/ConfigData
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1027)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.defineClassFwd(KnotClassLoader.java:160)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:355)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
	at draylar.inmis.Inmis.<clinit>(Inmis.java:49)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:534)
	at java.base/java.lang.Class.forName(Class.java:513)
	at net.fabricmc.loader.impl.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:50)
	at net.fabricmc.loader.impl.entrypoint.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:124)
	at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:53)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:399)
	... 9 more
Caused by: java.lang.ClassNotFoundException: me.shedaniel.autoconfig.ConfigData
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
	... 25 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:403)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:401)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:52)
	at net.minecraft.class_310.<init>(class_310.java:477)

-- Initialization --
Details:
	Modules: 
Stacktrace:
	at net.minecraft.client.main.Main.main(Main.java:239)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:100)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)

-- System Details --
Details:
	Minecraft Version: 1.21.1
	Minecraft Version ID: 1.21.1
	Operating System: Linux (amd64) version 6.10.6-zen1-1-zen
	Java Version: 21.0.4, Arch Linux
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Arch Linux
	Memory: 163311712 bytes (155 MiB) / 536870912 bytes (512 MiB) up to 8455716864 bytes (8064 MiB)
	CPUs: 2
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz
	Identifier: Intel64 Family 6 Model 78 Stepping 3
	Microarchitecture: Skylake (Client)
	Frequency (GHz): 2.60
	Number of physical packages: 1
	Number of physical CPUs: 2
	Number of logical CPUs: 2
	Graphics card #0 name: Skylake GT2 [HD Graphics 520]
	Graphics card #0 vendor: Intel Corporation (0x8086)
	Graphics card #0 VRAM (MiB): 256.00
	Graphics card #0 deviceId: 0x1916
	Graphics card #0 versionInfo: unknown
	Virtual memory max (MiB): 24255.16
	Virtual memory used (MiB): 6863.86
	Swap memory total (MiB): 16384.00
	Swap memory used (MiB): 0.00
	Space in storage for jna.tmpdir (MiB): <path not set>
	Space in storage for org.lwjgl.system.SharedLibraryExtractPath (MiB): <path not set>
	Space in storage for io.netty.native.workdir (MiB): <path not set>
	Space in storage for java.io.tmpdir (MiB): available: 5516.50, total: 7871.17
	Space in storage for workdir (MiB): available: 344390.38, total: 468341.69
	JVM Flags: 2 total; -Xms512m -Xmx8064m
	Fabric Mods: 
		fabric-api: Fabric API 0.102.1+1.21.1
			fabric-api-base: Fabric API Base 0.4.42+6573ed8c6a
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.68+b55973446a
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.29+5bd9f1bc6a
			fabric-block-api-v1: Fabric Block API (v1) 1.0.22+0af3f5a76a
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.10+6573ed8c6a
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.52+0af3f5a76a
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.15+6573ed8c6a
			fabric-command-api-v1: Fabric Command API (v1) 1.2.49+f71b366f6a
			fabric-command-api-v2: Fabric Command API (v2) 2.2.28+6ced4dd96a
			fabric-commands-v0: Fabric Commands (v0) 0.2.66+df3654b36a
			fabric-content-registries-v0: Fabric Content Registries (v0) 8.0.16+b55973446a
			fabric-convention-tags-v1: Fabric Convention Tags 2.0.20+7f945d5b6a
			fabric-convention-tags-v2: Fabric Convention Tags (v2) 2.6.0+605f22ad6a
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.29+0af3f5a76a
			fabric-data-attachment-api-v1: Fabric Data Attachment API (v1) 1.1.27+1daea2156a
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 20.2.17+16c4ae256a
			fabric-dimensions-v1: Fabric Dimensions API (v1) 4.0.0+6fc22b996a
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.6.12+6fc22b996a
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.7.12+ba9dae066a
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.53+6ced4dd96a
			fabric-item-api-v1: Fabric Item API (v1) 11.0.0+afdfc9216a
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.1.4+780172706a
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.47+0af3f5a76a
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.45+df3654b36a
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.3.12+6c1df3606a
			fabric-loot-api-v2: Fabric Loot API (v2) 3.0.14+3f89f5a56a
			fabric-loot-api-v3: Fabric Loot API (v3) 1.0.2+3f89f5a56a
			fabric-message-api-v1: Fabric Message API (v1) 6.0.13+6573ed8c6a
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 2.0.0+fe474d6b6a
			fabric-networking-api-v1: Fabric Networking API (v1) 4.2.2+60c3209b6a
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 15.2.0+40875a936a
			fabric-particles-v1: Fabric Particles (v1) 4.0.2+6573ed8c6a
			fabric-recipe-api-v1: Fabric Recipe API (v1) 5.0.12+650897126a
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 5.1.2+60c3209b6a
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.4.0+c705a49c6a
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.7.0+c705a49c6a
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.68+df3654b36a
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.48+73761d2e6a
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.1.6+1daea2156a
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.71+df3654b36a
			fabric-rendering-v1: Fabric Rendering (v1) 5.0.5+df16efd06a
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 4.3.0+8dc279b16a
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 1.3.0+565991296a
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.25+8b68f1c76a
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.86+b55973446a
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.23+6573ed8c6a
			fabric-transfer-api-v1: Fabric Transfer API (v1) 5.1.17+1db1cc1f6a
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 6.1.0+1daea2156a
		fabricloader: Fabric Loader 0.16.2
			mixinextras: MixinExtras 0.4.1
		inmis: Inmis 2.7.2-1.21.1
		java: OpenJDK 64-Bit Server VM 21
		minecraft: Minecraft 1.21.1
	Launched Version: 1.21.1
	Launcher name: PrismLauncher
	Backend library: LWJGL version 3.3.3-snapshot
	Backend API: Unknown
	Window size: <not initialized>
	GFLW Platform: <error>
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: <disabled>
	Is Modded: Definitely; Client brand changed to 'fabric'
	Universe: 404
	Type: Client (map_client.txt)
	Locale: en_FR
	System encoding: UTF-8
	File encoding: UTF-8
	CPU: <unknown>
```

Built using : 
```
/../inmis $ ./gradlew check
/../inmis $ ./gradlew build 
```

thanks
~lowusage

**Comment by Globox1997** [comment]
Since 1.21, draylars config mod is not updated so I moved to cloth config as a dependency.
